services:
  tvapp-bff:
    image: tvapp-bff
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5231:5231"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5231
