// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xiao.TVapp.Bff.Contexts;

#nullable disable

namespace Xiao.TVapp.Bff.Migrations
{
    [DbContext(typeof(StreamingUrlsContext))]
    partial class StreamingUrlsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Xiao.TVapp.Bff.Models.StreamingUrls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamingUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StreamingUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
